//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyPalaceApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consultation()
        {
            this.Status = new HashSet<Status>();
        }
    
        public int id { get; set; }
        public Nullable<int> service_id { get; set; }
        public Nullable<int> specialist_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> field_id { get; set; }
        public Nullable<System.TimeSpan> consultation_time { get; set; }
        public Nullable<System.DateTime> consultation_date { get; set; }
        public string notes { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Field Field { get; set; }
        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Status> Status { get; set; }
    }
}
