//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyPalaceApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialist
    {
        public int id { get; set; }
        public string full_name { get; set; }
        public Nullable<int> age { get; set; }
        public string gender { get; set; }
        public string email_address { get; set; }
        public string field { get; set; }
        public Nullable<int> field_id { get; set; }
    
        public virtual Field Field1 { get; set; }
    }
}
