//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyPalaceApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public int id { get; set; }
        public Nullable<int> consultation_id { get; set; }
        public string status_description { get; set; }
    
        public virtual Consultation Consultation { get; set; }
    }
}
