//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyPalaceApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class User1
    {
        public int id { get; set; }
        public string name { get; set; }
        public string login { get; set; }
        public string hash { get; set; }
        public string salt { get; set; }
    }
}
